version: "3.7" 

services:
  node:
    #image: "node:9.3"
    build: .
    user: "node"
    # user: "root"  
    working_dir: /home/node/app/hello-world
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8088:8088"
    command: "gatsby develop --host 0.0.0.0 --port 8088"